# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["local"]
  
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download latest data files
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "mnsrulz/hpqdata"
          latest: true
          fileName: "db.parquet"
          out-file-path: "assets"
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: whole-stoat-49 # the name of the project on Deno Deploy
          entrypoint: app/server.ts # the entrypoint to deploy
